autoplay execute action

diff --git a/bin/bzb b/bin/bzb
--- a/bin/bzb
+++ b/bin/bzb
@@ -1028,12 +1028,16 @@ main() {
     # Use ctrl-alt-t to open a new terminal/shell in current directory
     # Use ctrl-alt-e to execute a single command
     terminal|execute)
-      [[ "$action" = "execute" ]] && QUIT=';PROMPT_COMMAND="exit"' || QUIT=''
-      clear
-      set +e
-      # Trap each command to log previous command, commented out if exit status indicates failure
-      PS1='>> ' /usr/bin/env bash --init-file <(echo 'trap '\''export BZB_LAST_EXIT_CODE="$?" BZB_LAST_COMMAND="$BZB_THIS_COMMAND" BZB_THIS_COMMAND="$BASH_COMMAND";[[ "'${autorecord:+1}'" && "'${recording_file:+1}'" ]] && ([[ $BZB_LAST_EXIT_CODE -ne 0 ]] && printf "# (EXIT_CODE $BZB_LAST_EXIT_CODE) ";[[ $BZB_LAST_COMMAND ]] && printf "execute %q\n" "$BZB_LAST_COMMAND") >> '"$recording_file""$QUIT"\'' DEBUG')
-      set -e
+      if [[ $autoplay ]]; then
+        /usr/bin/env bash -c "${targets[@]}"
+      else
+        [[ "$action" = "execute" ]] && QUIT=';PROMPT_COMMAND="exit"' || QUIT=''
+        clear
+        set +e
+        # Trap each command to log previous command, commented out if exit status indicates failure
+        PS1='>> ' /usr/bin/env bash --init-file <(echo 'trap '\''export BZB_LAST_EXIT_CODE="$?" BZB_LAST_COMMAND="$BZB_THIS_COMMAND" BZB_THIS_COMMAND="$BASH_COMMAND";[[ "'${autorecord:+1}'" && "'${recording_file:+1}'" ]] && ([[ $BZB_LAST_EXIT_CODE -ne 0 ]] && printf "# (EXIT_CODE $BZB_LAST_EXIT_CODE) ";[[ $BZB_LAST_COMMAND ]] && printf "execute %q\n" "$BZB_LAST_COMMAND") >> '"$recording_file""$QUIT"\'' DEBUG')
+        set -e
+      fi
     ;;
 
   # Fall through to remaining cases
