set minimum bash version

diff --git a/bin/bzb b/bin/bzb
--- a/bin/bzb
+++ b/bin/bzb
@@ -1,6 +1,11 @@
 #!/bin/bash
 set -e
 
+if [[ "${BASH_VERSINFO[0]}" -lt 2 ]]; then
+  echo "Error: $(basename "${BASH_SOURCE[0]}") requires a newer version of bash" 1>&2
+  exit 1
+fi
+
 # bind readline macros for cancelling prompts with ctr-g or double-escape
 bind '"\C-g":"\C-k\C-u
 "' '"\e\e":"\C-g"' &>/dev/null
