improve project scaffolding

diff --git a/init-deps b/init-deps
--- a/init-deps
+++ b/init-deps
@@ -1,16 +1,24 @@
 #!/bin/bash
 
-# Create a symlink to each dependency in .deps directory
-if [[ -d $PROJECT_DEP_DIR ]]; then
-    mkdir ./.deps
-    IFS=" "
-    for dep in $PROJECT_DEPENDENCIES; do
-        ln -s "$PROJECT_DEP_DIR/$dep" .deps/
-    done
-    unset IFS
-fi
+# Pull in project dependencies if they are defined
+if [[ -n "$PROJECT_DEPENDENCIES" && -d "$PROJECT_DEP_DIR" ]]; then
 
-# Copy files for each dependency in '.deps' (Including nested dependencies)
-# NOTE: "bash -c" is used to enable glob expansion
-find -L .deps -iname '.deps' -exec bash -c "rsync -Lr --ignore-existing --exclude .deps {}\/*/ ." \;
+  # Fail if '.deps' directory already exists
+  if [[ -e .deps ]]; then
+    echo "ERROR: '.deps' directory already exists!" 1>&2
+    exit 1
+  fi
+
+  # Create a symlink to each dependency in .deps directory
+  mkdir ./.deps
+  IFS=" "
+  for dep in $PROJECT_DEPENDENCIES; do
+    ln -s "$PROJECT_DEP_DIR/$dep" .deps/
+  done
+  unset IFS
+
+  # Copy files for each dependency in '.deps' (Including nested dependencies)
+  # NOTE: "bash -c" is used to enable glob expansion
+  find -L .deps -iname '.deps' -exec bash -c "rsync -Lr --ignore-existing --exclude .deps {}\/*/ ." \;
+fi
 
diff --git a/init-node-project b/init-node-project
--- a/init-node-project
+++ b/init-node-project
@@ -6,18 +6,38 @@ init-deps
 # Setup 'package.json', initializing 'base.package.json' if necessary.
 init-package-json
 
+# Optionally generate manifest using variables auto-loaded from entry.sh
+if [[ -n "$PROJECT_MANIFEST" ]]; then
+
+  # Fail if manifest already exists
+  if [[ -e "$PROJECT_MANIFEST" ]]; then
+    echo "ERROR: file '$PROJECT_MANIFEST' already exists!" 1>&2
+    exit 1
+  fi
+
+  echo-file "$HOME/.skeletons/bash/$PROJECT_MANIFEST" > "$PROJECT_MANIFEST"
+
+  # Fail if manifest does not exist or is empty
+  if [[ ! "$PROJECT_MANIFEST" ]]; then
+    echo "ERROR: file '$PROJECT_MANIFEST' not found or contains no data." 1>&2
+    exit 1
+  fi
+
+fi
+
 # Setup '.babelrc' if babel configuration is present.
 if [[ -d 'conf/babel' ]]; then
     init-babelrc
 fi
 
+# Setup '.babelrc' if babel configuration is present.
 # Install packages, using 'yarn' if it exists in user's path.
 npm=$(which npm)
 if [[ ! -x "$npm" ]]; then
     echo "ERROR: Could not find 'npm' executable in path." 1>&2
-    exit 1
+    exit 3
 fi
-yarn=$(which yarn)
+yarn=$(which yarn 2>/dev/null)
 if [[ -x "$yarn" ]] ; then
     yarn
 else
