Reduce steps to scaffold node projects.

diff --git a/init-package-json b/init-package-json
--- a/init-package-json
+++ b/init-package-json
@@ -5,19 +5,28 @@
 # jq - a lightweight and flexible command-line JSON processor.
 # https://stedolan.github.io/jq/download/
 
-# Fail if base.package.json does not exist
-if [[ ! -e base.package.json ]]; then
-    echo "ERROR: file 'base.package.json' not found." 1>&2
+# Fail if '.entry.sh' does not exist or is empty
+if [[ ! -s .entry.sh ]]; then
+    echo "ERROR: file '.entry.sh' not found or contains no data." 1>&2
     exit 1
 fi
 
-# Fail if package.json already exists
+# Vim is configured to auto-generate 'package.json' from data in '.entry.sh'
+vim +wq "base.package.json"
+
+# Fail if 'base.package.json' does not exist or is empty
+if [[ ! -s base.package.json ]]; then
+    echo "ERROR: file 'base.package.json' not found or contains no data." 1>&2
+    exit 1
+fi
+
+# Fail if 'package.json' already exists
 if [[ -e package.json ]]; then
     echo "ERROR: file 'package.json' already exists!" 1>&2
     exit 1
 fi
 
-# Create new package.json by merging base with packages from dependencies
-# Attribution: Array-merge jq-script courtesy of William Langford
+# Create new 'package.json' by merging base with packages from dependencies
+# Attribution: Array-merge jq script courtesy of William Langford, https://github.com/stedolan/jq/issues/502
 cat "base.package.json" `find -L "conf/packages" -not -path '*node_modules*' -type f -iname "*.json"` | jq -s '[.[] | to_entries] | flatten | reduce .[] as $dot ({}; .[$dot.key] += $dot.value)' > "package.json"
 
